import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        '01-getting-started/README',
        '01-getting-started/prerequisites',
        '01-getting-started/installation',
        '01-getting-started/quick-start',
        '01-getting-started/first-deployment',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: true,
      items: [
        '02-architecture/README',
        '02-architecture/overview',
        '02-architecture/infrastructure-tiers',
        '02-architecture/network-design',
        '02-architecture/security-model',
        '02-architecture/vm-id-ranges',
      ],
    },
    {
      type: 'category',
      label: 'Layers',
      collapsed: true,
      items: [
        '03-layers/README',
        '03-layers/datacenter',
        '03-layers/compute',
        '03-layers/networking',
        '03-layers/databases',
        '03-layers/cluster',
        '03-layers/security',
        '03-layers/observability',
        '03-layers/apps',
      ],
    },
    {
      type: 'category',
      label: 'Services',
      collapsed: true,
      items: [
        '04-services/README',
        '04-services/vyos-firewall',
        '04-services/powerdns',
        '04-services/dnsdist',
        '04-services/headscale-vpn',
        '04-services/keycloak-iam',
        '04-services/openbao-secrets',
        '04-services/postgresql-patroni',
        '04-services/redis-sentinel',
        '04-services/prometheus-monitoring',
        '04-services/grafana-dashboards',
        '04-services/loki-logging',
        '04-services/alertmanager',
        '04-services/wazuh-siem',
      ],
    },
    {
      type: 'category',
      label: 'Kubernetes',
      collapsed: true,
      items: [
        '05-kubernetes/README',
        '05-kubernetes/cluster-architecture',
        '05-kubernetes/cilium-cni',
        '05-kubernetes/traefik-ingress',
        '05-kubernetes/cert-manager',
        '05-kubernetes/velero-backup',
        '05-kubernetes/argocd-gitops',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      collapsed: true,
      items: [
        '06-operations/README',
        '06-operations/deployment-workflow',
        '06-operations/validation',
        '06-operations/apply-changes',
        '06-operations/rollback',
        '06-operations/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Runbooks',
      collapsed: true,
      items: [
        '07-runbooks/README',
        '07-runbooks/emergency-access',
        '07-runbooks/cluster-recovery',
        '07-runbooks/database-failover',
        '07-runbooks/secret-rotation',
        '07-runbooks/incident-response',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        '08-reference/README',
        '08-reference/cli-commands',
        '08-reference/platform-yaml-schema',
        '08-reference/infrastructure-requirements',
        '08-reference/vm-id-ranges',
        {
          type: 'category',
          label: 'Types',
          collapsed: true,
          items: [
            '08-reference/types/README',
            {
              type: 'category',
              label: 'Core Types',
              collapsed: true,
              items: [
                '08-reference/types/Platform',
                '08-reference/types/Datacenter',
                '08-reference/types/ComputeConfig',
                '08-reference/types/K8sCluster',
              ],
            },
            {
              type: 'category',
              label: 'Layer Configuration',
              collapsed: true,
              items: [
                '08-reference/types/NetworkingConfig',
                '08-reference/types/DatabaseCluster',
                '08-reference/types/SecurityConfig',
                '08-reference/types/AppsConfig',
              ],
            },
            {
              type: 'category',
              label: 'Types VM',
              collapsed: true,
              items: [
                '08-reference/types/VMBase',
                '08-reference/types/VMBasedOnType',
                '08-reference/types/VMCustom',
                '08-reference/types/ComputeType',
                '08-reference/types/VMRole',
              ],
            },
            {
              type: 'category',
              label: 'Network Types',
              collapsed: true,
              items: [
                '08-reference/types/DNSConfig',
                '08-reference/types/VPNConfig',
                '08-reference/types/FirewallConfig',
                '08-reference/types/FloatingIP',
                '08-reference/types/PublicIPConfig',
              ],
            },
            {
              type: 'category',
              label: 'Security Types',
              collapsed: true,
              items: [
                '08-reference/types/SSOConfig',
                '08-reference/types/VaultConfig',
                '08-reference/types/CertManagerConfig',
                '08-reference/types/CredentialRef',
              ],
            },
            {
              type: 'category',
              label: 'Utility Types',
              collapsed: true,
              items: [
                '08-reference/types/StorageBackend',
                '08-reference/types/Feature',
                '08-reference/types/DatabaseDefinition',
                '08-reference/types/ServerDescriptionType',
              ],
            },
            {
              type: 'category',
              label: 'Operational Types',
              collapsed: true,
              items: [
                '08-reference/types/ValidationResult',
                '08-reference/types/PlanResult',
              ],
            },
            {
              type: 'category',
              label: 'Enumerations',
              collapsed: true,
              items: [
                '08-reference/types/InfrastructureTierType',
                '08-reference/types/LayerType',
                '08-reference/types/BackendType',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Deep Dive',
      collapsed: true,
      items: [
        '10-deep-dive/01-index',
        '10-deep-dive/02-datacenter-bootstrap',
        '10-deep-dive/03-why-software-mesh',
        '10-deep-dive/04-why-software-mesh-opt',
        '10-deep-dive/05-vms',
      ],
    },
    {
      type: 'category',
      label: 'Appendix',
      collapsed: true,
      items: [
        '99-appendix/README',
        '99-appendix/glossary',
        '99-appendix/faq',
        '99-appendix/changelog',
      ],
    },
  ],
};

export default sidebars;
