import { InitOptions, getPrimaryRegion, getPrimaryZone } from "./index";
import ora from "ora";
import fs from "fs";
import path from "path";

export const createReadme = async (options: InitOptions): Promise<void> => {
  const spinner = ora("Creating README.md").start();
  const projectPath = path.resolve(process.cwd(), options.projectName);

  try {
    const tier = options.infrastructureTier || "production";
    const regions = options.regions || [{ name: "eu", zones: ["main"] }];
    const primaryRegion = getPrimaryRegion(options);
    const primaryZone = getPrimaryZone(options);

    const filePath = path.join(projectPath, "README.md");
    const content = generateReadme(options.projectName, tier, regions, primaryRegion.name, primaryZone);

    fs.writeFileSync(filePath, content);
    spinner.succeed("README.md created");
  } catch (error) {
    spinner.fail("Failed to create README.md");
    throw error;
  }
};

function generateReadme(
  projectName: string,
  tier: string,
  regions: { name: string; zones: string[] }[],
  primaryRegionName: string,
  primaryZone: string
): string {
  // Get all zones
  const allZones: string[] = [];
  regions.forEach((r) => r.zones.forEach((z) => allZones.push(z)));
  const isMultiZone = allZones.length > 1;
  const isMultiRegion = regions.length > 1;

  return `# ${projectName}

Soverstack infrastructure project

## Project Information

- **Tier**: ${tier}
- **Regions**: ${regions.map((r) => r.name).join(", ")}
- **Primary**: ${primaryRegionName}/${primaryZone}
- **Created**: ${new Date().toISOString().split("T")[0]}

## Quick Start

### 1. Configure your environment

Edit the \`.env\` file with your credentials:
\`\`\`bash
POSTGRES_ADMIN_PASSWORD=your-secure-password
REDIS_PASSWORD=your-redis-password
SOVERSTACK_ADMIN_PASSWORD=your-admin-password
\`\`\`

### 2. Configure Regions and Zones

\`\`\`bash
# Global configuration
vim platform.yaml
vim core-compute.yaml
vim core-database.yaml

# Region configuration
${regions.map((r) => `vim regions/${r.name}/region.yaml`).join("\n")}

# Zone configurations
${regions.flatMap((r) => r.zones.map((z) => `vim regions/${r.name}/zones/${z}/datacenter.yaml`)).join("\n")}
\`\`\`

### 3. Validate Configuration

\`\`\`bash
soverstack validate platform.yaml
\`\`\`

### 4. Apply Infrastructure

\`\`\`bash
soverstack apply platform.yaml
\`\`\`

## Project Structure

\`\`\`
${projectName}/
├── platform.yaml              # Root configuration
├── orchestrator.yaml          # API, PDM
├── security.yaml              # Vault, Keycloak, Teleport
├── networking.yaml            # Headscale, PowerDNS
├── observability.yaml         # Grafana, Uptime Kuma
├── core-compute.yaml          # Global VMs
├── core-database.yaml         # PostgreSQL
├── ssh_config.yaml
├── .env                       # Secrets (DO NOT COMMIT!)
│
└── regions/
${regions.map((r) => `    └── ${r.name}/
        ├── region.yaml
        ├── observability.yaml     # Regional config
        ├── core-compute.yaml      # Prometheus, Loki, Alertmanager
        ├── hub/
        │   ├── backup.yaml
        │   └── core-compute.yaml  # PBS, MinIO
        └── zones/
${r.zones.map((z) => `            └── ${z}/
                ├── datacenter.yaml
                ├── networking.yaml
                └── core-compute.yaml  # VyOS, HAProxy`).join("\n")}`).join("\n")}
\`\`\`

## Architecture

### Three-Level Hierarchy

| Level | Services | Deployed On |
|-------|----------|-------------|
| **Global** | Vault, Keycloak, PostgreSQL, Grafana, Wazuh | ${primaryRegionName}/${primaryZone} |
| **Regional** | Prometheus, Loki, Alertmanager | First zone of each region |
| **Zone** | VyOS, HAProxy | Each zone |

### Regions & Zones

${regions.map((r) => `- **${r.name}**: ${r.zones.join(", ")}${r.name === primaryRegionName ? " (primary)" : ""}`).join("\n")}

## Security

- **VPN**: All admin access via Headscale
- **SSH**: Via Teleport bastion
- **Secrets**: Vault/OpenBao
- **Never commit**: \`.env\`, SSH keys, credentials

## Commands

\`\`\`bash
# Validate
soverstack validate platform.yaml

# Plan changes
soverstack plan platform.yaml

# Apply
soverstack apply platform.yaml

# Destroy
soverstack destroy platform.yaml
\`\`\`

---
Generated by Soverstack v1.0.0
`;
}
